Performance
koikiss-dev/jimov_api pull request #152
Opened 2024-03-02 22:39 UTC by koikiss-dev

2024-03-03 01:58 UTC, barrientosvctor requested changes
I highly recommend to use `import type { }` / `import { type ... }` when importing a type instead of using `import {}`. This increases the app performance and it's only supported for TypeScript files.

- [Source](https://medium.com/@quizzesforyou/import-vs-import-type-in-typescript-8e5177b62bea)

2024-03-03 04:46 UTC, Mawfyy reviewed
I like this change, more modular but, i prefer quit commented code from branch like dev or main.

2024-03-03 04:46 UTC, Mawfyy commented on src/scraper/sites/anime/animelatinohd/AnimeLatinoHD.ts
> +            //const min = await axios.get("https://filemoon.sx/e/smone1s7jjxv/CYM01HNMCGTSKT")
Please, don't put commented code, delete or do whatever you want with that code.

2024-03-03 04:46 UTC, Mawfyy commented on src/scraper/sites/anime/animelatinohd/AnimeLatinoHD.ts
> +            //const cookies = [{name: 'v_id', value: "https://api.animelatinohd.com/stream/"+e.id},];
Please, don't put commented code, delete or do whatever you want with that code.

2024-03-03 04:46 UTC, Mawfyy commented on src/scraper/sites/anime/animelatinohd/AnimeLatinoHD.ts
> +            //await pageload.page.setCookie(...cookies)
Please, don't put commented code, delete or do whatever you want with that code.

2024-03-03 04:46 UTC, Mawfyy commented on src/scraper/sites/anime/gogoanime/Gogoanime.ts
> +/* import { getHTML } from "./assets/getHTML";
Please, don't put commented code, delete or do whatever you want with that code.

2024-03-22 04:08 UTC, barrientosvctor approved these changes
It looks great. Good job!

2024-03-22 04:10 UTC, barrientosvctor commented
btw, remember to resolve the conflicts on `Monoschinos.ts`. The most recent change was in dev branch.

2024-03-28 01:45 UTC, merged